#ifndef QTLIBCHECKBOX_GLOBAL_H
#define QTLIBCHECKBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTLIBCHECKBOX_LIBRARY)
#  define QTLIBCHECKBOXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTLIBCHECKBOXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTLIBCHECKBOX_GLOBAL_H
